#! /bin/bash
### BEGIN INIT INFO
# Provides:          bigredbutton
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       service for running bigredbutton-py
#
APPNAME=bigredbutton
APP_PATH=/var/www/html/bigredbutton-py/src
USER=lynx
PATH=/bin:/usr/bin:/sbin:/usr/sbin
ACTIVATE=bigredbutton_activate
#APPMODULE=yourproject.wsgi:application
APPMODULE=run:app
DAEMON=gunicorn
DAEMON_PATH=/var/www/html/bigredbutton-py/src/brb_env/bin
#BIND=0.0.0.0:8000
BIND=unix:/var/run/$APPNAME.sock
PIDFILE=/var/run/$APPNAME.pid
LOGDIR=/var/log/$APPNAME
LOGFILE=$LOGDIR/$DAEMON.log
WORKERS=2
WORKER_CLASS="gevent"

# Source function library.
. /etc/rc.d/init.d/functions
#. /lib/lsb/init-functions

. /etc/profile.d/bigredbutton.sh


if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi

if [ ! -d "$LOGDIR" ]; then
  mkdir -p $LOGDIR
fi


case "$1" in
  start)
        echo "Starting python application:  $APPNAME"
        $ACTIVATE
        cd $APP_PATH
        echo "$DAEMON --daemon --bind=$BIND --pid=$PIDFILE --name=$APPNAME --workers=$WORKERS --worker-class=$WORKER_CLASS --user=$USER --log-file=$LOGFILE $APPMODULE"
        $DAEMON --daemon --bind=$BIND --pid=$PIDFILE --name=$APPNAME --workers=$WORKERS --worker-class=$WORKER_CLASS --user=$USER --log-file=$LOGFILE $APPMODULE
        echo $?
    ;;
  stop)
        echo "Stopping python application: $APPNAME"
        killproc -p $PIDFILE $DAEMON
        echo $?
    ;;
  reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status $APPNAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|reload|status}"
    exit 1
    ;;
esac

exit 0
