#! /bin/bash
### BEGIN INIT INFO
# Provides:          yourapp
# Required-Start:    nginx
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The main django process
# Description:       The gunicorn process that receives HTTP requests
#                    from nginx
#
### END INIT INFO
#
# Author:       mle <geobi@makina-corpus.net>
#
APPNAME=bigredbutton
USER=lynx
PATH=/bin:/usr/bin:/sbin:/usr/sbin
ACTIVATE=/var/www/html/bigredbutton-py/src/brb_env/bin/activate
#APPMODULE=yourproject.wsgi:application
APPMODULE=run:app
DAEMON=gunicorn
BIND=127.0.0.1:8000
PIDFILE=/var/run/gunicorn.pid
LOGFILE=/var/log/$DAEMON.log
WORKERS=2
WORKER_CLASS="gevent"

# Source function library.
. /etc/rc.d/init.d/functions
#. /lib/lsb/init-functions


if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi


case "$1" in
  start)
        echo "Starting deferred execution scheduler" "$APPNAME"
        source $ACTIVATE
        $DAEMON --daemon --bind=$BIND --pid=$PIDFILE --workers=$WORKERS --worker-class=$WORKER_CLASS --user=$USER --log-file=$LOGFILE $APPMODULE
        echo $?
    ;;
  stop)
        echo "Stopping deferred execution scheduler" "APPNAME"
        killproc -p $PIDFILE $DAEMON
        echo $?
    ;;
  reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status $APPNAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|reload|status}"
    exit 1
    ;;
esac

exit 0
